// DAYFLOW HRMS — ADMIN REPORTS VIEW (/admin/reports)
// Every report is generated by the backend reporting API:
//   GET /api/admin/reports/attendance | leaves | payroll | employees
// CSV downloads stream from the same endpoints (format=csv).

import { adminStore, formatINR } from '../../core/adminStore.js';
import { esc, todayISO, currentMonthKey, fmtTime, hoursLabel } from '../../core/api.js';
import { renderAdminLayout, initAdminLayoutEvents, rerenderPageContent } from '../../components/admin/AdminLayout.js';
import { EmptyState } from '../../components/admin/EmptyState.js';
import { EmployeeSelectOptions, DepartmentOptions } from '../../components/admin/AttendanceFilters.js';
import { AttendanceTable } from '../../components/admin/AttendanceTable.js';
import { StatusBadge } from '../../components/admin/StatusBadge.js';
import { showToast } from '../../components/Toast.js';

const REPORT_TYPES = [
  { value: 'attendance', label: 'Attendance Report' },
  { value: 'leaves', label: 'Leave Report' },
  { value: 'payroll', label: 'Payroll Report' },
  { value: 'employees', label: 'Employee Report' },
];

const LEAVE_TYPE_LABELS = {
  PTO: 'Paid Time Off',
  SICK: 'Sick Leave',
  UNPAID: 'Unpaid Leave',
};

export function createAdminReportsView() {
  const ui = {
    employeesLoaded: false,
    error: null,
    reportType: 'attendance',
    employeeId: '',
    department: '',
    status: '',
    leaveType: '',
    month: currentMonthKey(),
    startDate: `${currentMonthKey()}-01`,
    endDate: todayISO(),
    search: '',
    generating: false,
    generateError: '',
    result: null, // { type, data }
  };

  // ------------------------------------------------------------------ HELPERS

  const empName = (e) => `${e?.firstName || ''} ${e?.lastName || ''}`.trim() || 'Unknown';
  const dayOf = (iso) => String(iso || '').slice(0, 10);

  const chip = (label, cls) =>
    `<span class="badge ${cls}" style="font-size:13px; padding:6px 14px;">${esc(label)}</span>`;

  function buildFilters() {
    return adminStore.reportFilters({
      from: ui.startDate,
      to: ui.endDate,
      department: ui.department,
      status: ui.status,
      employeeId: ui.employeeId,
      leaveType: ui.leaveType,
    });
  }

  // ------------------------------------------------------------- SKELETONS

  function skeletonHtml() {
    return `
      <div class="skeleton" style="height:150px; border-radius:16px; margin-bottom:20px;"></div>
      <div class="skeleton" style="height:360px; border-radius:16px;"></div>
    `;
  }

  function errorHtml() {
    return `
      <div style="padding:40px; text-align:center;">
        <i data-lucide="alert-triangle" style="width:36px; height:36px; color:var(--danger);"></i>
        <div style="font-weight:600; margin-top:12px;">Could not load reports</div>
        <div style="font-size:13px; color:var(--text-tertiary); margin-top:4px;">${esc(ui.error || 'Unknown error')}</div>
        <button class="btn btn-primary btn-sm" id="rep-retry" style="margin-top:16px;">Retry</button>
      </div>
    `;
  }

  // ---------------------------------------------------------------- CONTROLS

  function statusOptionsHtml() {
    const opts = ui.reportType === 'leaves'
      ? ['PENDING', 'APPROVED', 'REJECTED']
      : ['PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE'];
    return `
      <option value="">All Statuses</option>
      ${opts.map(s => `<option value="${s}" ${ui.status === s ? 'selected' : ''}>${esc(s.replace(/_/g, '-'))}</option>`).join('')}
    `;
  }

  function controlsHtml() {
    const showDates = ui.reportType === 'attendance' || ui.reportType === 'leaves';
    return `
      <div class="card" style="margin-bottom:24px;">
        <div class="report-controls">
          <div class="filter-group" style="max-width:none;">
            <label class="filter-label required" for="rep-type">Report Type</label>
            <select id="rep-type" class="form-select">
              ${REPORT_TYPES.map(t => `<option value="${t.value}" ${ui.reportType === t.value ? 'selected' : ''}>${t.label}</option>`).join('')}
            </select>
          </div>

          ${ui.reportType !== 'employees' ? `
          <div class="filter-group" style="max-width:none;">
            <label class="filter-label" for="rep-employee">Employee</label>
            <select id="rep-employee" class="form-select">
              <option value="">All Employees</option>
              ${EmployeeSelectOptions(ui.employees, ui.employeeId)}
            </select>
          </div>` : ''}

          <div class="filter-group" style="max-width:none;">
            <label class="filter-label" for="rep-dept">Department</label>
            <select id="rep-dept" class="form-select">
              <option value="">All Departments</option>
              ${DepartmentOptions(ui.department)}
            </select>
          </div>

          ${showDates ? `
          <div class="filter-group" style="max-width:none;">
            <label class="filter-label required" for="rep-start">Date Range</label>
            <div class="date-range-group">
              <input type="date" id="rep-start" class="form-input" value="${esc(ui.startDate)}" />
              <span style="color:var(--text-tertiary);">to</span>
              <input type="date" id="rep-end" class="form-input" value="${esc(ui.endDate)}" />
            </div>
          </div>` : ''}

          ${ui.reportType === 'payroll' ? `
          <div class="filter-group" style="max-width:none;">
            <label class="filter-label" for="rep-month">Pay Period</label>
            <input type="month" id="rep-month" class="form-input" value="${esc(ui.month)}" />
          </div>` : ''}

          ${(showDates && !['payroll', 'employees'].includes(ui.reportType)) ? `
          <div class="filter-group" style="max-width:none;">
            <label class="filter-label" for="rep-status">Status</label>
            <select id="rep-status" class="form-select">${statusOptionsHtml()}</select>
          </div>` : ''}

          ${ui.reportType === 'leaves' ? `
          <div class="filter-group" style="max-width:none;">
            <label class="filter-label" for="rep-leave-type">Leave Type</label>
            <select id="rep-leave-type" class="form-select">
              <option value="">All Types</option>
              ${Object.entries(LEAVE_TYPE_LABELS).map(([v, l]) => `<option value="${v}" ${ui.leaveType === v ? 'selected' : ''}>${l}</option>`).join('')}
            </select>
          </div>` : ''}

          ${ui.reportType === 'employees' ? `
          <div class="filter-group grow-lg" style="max-width:none;">
            <label class="filter-label" for="rep-search">Search</label>
            <input type="text" id="rep-search" class="form-input" placeholder="Name, email or ID..." value="${esc(ui.search)}" />
          </div>` : ''}
        </div>

        <div style="display:flex; gap:10px; flex-wrap:wrap;">
          <button class="btn btn-primary" id="rep-generate-btn" ${ui.generating ? 'disabled' : ''}>
            ${ui.generating
              ? '<i data-lucide="loader-2" style="width:15px;height:15px; animation: spin 1s linear infinite;"></i> Generating…'
              : '<i data-lucide="play" style="width:15px;height:15px;"></i> Generate Report'}
          </button>
          <button class="btn btn-secondary" id="rep-export-csv-btn" ${!ui.result || ui.generating ? 'disabled' : ''}>
            <i data-lucide="download" style="width:15px;height:15px;"></i> Export CSV
          </button>
        </div>
      </div>
    `;
  }

  // ---------------------------------------------------------------- PREVIEW

  function previewAreaHtml() {
    if (ui.generateError) {
      return `
        <div class="error-state card" style="align-items:flex-start;">
          <div style="display:flex; gap:12px; align-items:center; width:100%;">
            <i data-lucide="alert-triangle" style="width:22px;height:22px;color:var(--danger);"></i>
            <p style="color:var(--danger); font-size:14px; font-weight:500;">${esc(ui.generateError)}</p>
          </div>
        </div>
      `;
    }
    if (ui.generating) {
      return '<div class="skeleton" style="height:360px; border-radius:16px;"></div>';
    }
    if (!ui.result) {
      return EmptyState({
        icon: 'clipboard-list',
        title: 'No report generated yet',
        desc: 'Choose a report type, adjust the filters and press Generate Report.',
      });
    }

    const body = {
      attendance: attendanceResultHtml,
      leaves: leavesResultHtml,
      payroll: payrollResultHtml,
      employees: employeesResultHtml,
    }[ui.result.type]();

    return `<div class="card">${body}</div>`;
  }

  function attendanceResultHtml() {
    const { summary, records } = ui.result.data;
    return `
      <div class="card-header">
        <h3 class="card-title"><i data-lucide="calendar-check" style="width:18px;height:18px;color:var(--primary);"></i><span>Attendance Report</span></h3>
        <span style="font-size:12px; color:var(--text-tertiary);">${esc(ui.startDate)} → ${esc(ui.endDate)}</span>
      </div>
      <div style="display:flex; gap:10px; flex-wrap:wrap; margin-bottom:18px;">
        ${chip(`${summary.totalRecords} records`, 'badge-info')}
        ${chip(`${summary.present} present`, 'badge-success')}
        ${chip(`${summary.absent} absent`, 'badge-warning')}
        ${chip(`${summary.halfDay} half-days`, 'badge-warning')}
        ${chip(`${summary.leave} leave`, 'badge-info')}
        ${chip(`work ${hoursLabel(summary.totalWorkHours)}`, 'badge-success')}
        ${chip(`extra ${hoursLabel(summary.totalExtraHours)}`, 'badge-success')}
      </div>
      ${AttendanceTable([
        { label: 'Date', render: r => `<span class="cell-strong">${esc(dayOf(r.date))}</span>` },
        { label: 'Employee', render: r => esc(empName(r.employee)) },
        { label: 'ID', render: r => esc(r.employee?.loginId || '') },
        { label: 'Department', render: r => esc(r.employee?.department || '-') },
        { label: 'Check In', render: r => (r.checkInTime ? esc(fmtTime(r.checkInTime)) : '--:--') },
        { label: 'Check Out', render: r => (r.checkOutTime ? esc(fmtTime(r.checkOutTime)) : '--:--') },
        { label: 'Work Hours', render: r => hoursLabel(r.workHours) },
        { label: 'Extra Hours', render: r => (Number(r.extraHours) > 0 ? `<span style="color:var(--success); font-weight:600;">${hoursLabel(r.extraHours)}</span>` : hoursLabel(r.extraHours)) },
        { label: 'Status', render: r => StatusBadge(r.status) },
      ], records || [], { minWidthClass: 'table-min-960', emptyMessage: 'No attendance records match these filters.' })}
    `;
  }

  function leavesResultHtml() {
    const { summary, records } = ui.result.data;
    return `
      <div class="card-header">
        <h3 class="card-title"><i data-lucide="calendar-days" style="width:18px;height:18px;color:var(--primary);"></i><span>Leave Report</span></h3>
        <span style="font-size:12px; color:var(--text-tertiary);">${esc(ui.startDate)} → ${esc(ui.endDate)}</span>
      </div>
      <div style="display:flex; gap:10px; flex-wrap:wrap; margin-bottom:18px;">
        ${chip(`${summary.totalRequests} requests`, 'badge-info')}
        ${chip(`${summary.pending} pending`, 'badge-warning')}
        ${chip(`${summary.approved} approved`, 'badge-success')}
        ${chip(`${summary.rejected} rejected`, 'badge-danger')}
        ${chip(`${Number(summary.totalDaysRequested ?? 0)} days requested`, 'badge-info')}
      </div>
      ${AttendanceTable([
        { label: 'Start', render: r => `<span class="cell-strong">${esc(dayOf(r.startDate))}</span>` },
        { label: 'End', render: r => esc(dayOf(r.endDate)) },
        { label: 'Employee', render: r => esc(empName(r.employee)) },
        { label: 'ID', render: r => esc(r.employee?.loginId || '') },
        { label: 'Type', render: r => esc(LEAVE_TYPE_LABELS[r.leaveType] || r.leaveType) },
        { label: 'Days', render: r => esc(String(r.requestedDays ?? '-')) },
        { label: 'Status', render: r => StatusBadge(r.status) },
        { label: 'Decided By', render: r => esc(r.decidedBy?.email || '—') },
      ], records || [], { minWidthClass: 'table-min-880', emptyMessage: 'No leave requests match these filters.' })}
    `;
  }

  function payrollResultHtml() {
    const { summary, records } = ui.result.data;
    return `
      <div class="card-header">
        <h3 class="card-title"><i data-lucide="wallet" style="width:18px;height:18px;color:var(--primary);"></i><span>Payroll Report</span></h3>
        <span style="font-size:12px; color:var(--text-tertiary);">${esc(ui.month || 'All periods')}</span>
      </div>
      <div style="display:flex; gap:10px; flex-wrap:wrap; margin-bottom:18px;">
        ${chip(`${summary.payslipCount} payslip(s)`, 'badge-info')}
        ${chip(`Gross ${formatINR(summary.totalGross)}`, 'badge-success')}
        ${chip(`Net ${formatINR(summary.totalNetPay)}`, 'badge-success')}
        ${chip(`EE PF ${formatINR(summary.totalEmployeePf)}`, 'badge-warning')}
        ${chip(`ER PF ${formatINR(summary.totalEmployerPf)}`, 'badge-warning')}
        ${chip(`PT ${formatINR(summary.totalProfessionalTax)}`, 'badge-warning')}
      </div>
      ${AttendanceTable([
        { label: 'Period', render: p => `<span class="cell-strong">${esc(`${p.periodYear}-${String(p.periodMonth).padStart(2, '0')}`)}</span>` },
        { label: 'Employee', render: p => esc(empName(p.employee)) },
        { label: 'ID', render: p => esc(p.employee?.loginId || '') },
        { label: 'Department', render: p => esc(p.employee?.department || '-') },
        { label: 'Gross', render: p => formatINR(p.grossEarnings) },
        { label: 'Net Pay', render: p => `<span class="cell-strong" style="color:var(--success);">${formatINR(p.netPay)}</span>` },
      ], records || [], { minWidthClass: 'table-min-720', emptyMessage: 'No payslips found for this period.' })}
    `;
  }

  function employeesResultHtml() {
    const { totalEmployees, byDepartment, employees } = ui.result.data;
    return `
      <div class="card-header">
        <h3 class="card-title"><i data-lucide="users" style="width:18px;height:18px;color:var(--primary);"></i><span>Employee Report</span></h3>
        <span style="font-size:12px; color:var(--text-tertiary);">${ui.search ? `Search: "${esc(ui.search)}"` : 'Full directory'}</span>
      </div>
      <div style="display:flex; gap:10px; flex-wrap:wrap; margin-bottom:18px;">
        ${chip(`${totalEmployees} employee(s)`, 'badge-info')}
        ${Object.entries(byDepartment || {}).map(([d, c]) => chip(`${d}: ${c}`, 'badge-info')).join('')}
      </div>
      ${AttendanceTable([
        { label: 'ID', render: e => esc(e.loginId || '') },
        { label: 'Name', render: e => `<span class="cell-strong">${esc(empName(e))}</span>` },
        { label: 'Email', render: e => esc(e.email || '-') },
        { label: 'Phone', render: e => esc(e.phone || '-') },
        { label: 'Department', render: e => esc(e.department || '-') },
        { label: 'Designation', render: e => esc(e.designation || '-') },
        { label: 'Joined', render: e => esc(dayOf(e.joiningDate)) },
        { label: 'Role', render: e => esc((e.user?.role || '').replace('_', '-')) },
        { label: 'Status', render: e => StatusBadge(e.user?.status || 'ACTIVE') },
      ], employees || [], { minWidthClass: 'table-min-960', emptyMessage: 'No employees match these filters.' })}
    `;
  }

  // ------------------------------------------------------------------- RENDER

  function contentHtml() {
    return `
      <div style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:12px; margin-bottom:20px;">
        <div>
          <h2 style="font-size:22px; font-weight:700; letter-spacing:-0.4px;">Reports</h2>
          <p style="color:var(--text-secondary); font-size:13px; margin-top:2px;">Generate and export live company reports.</p>
        </div>
      </div>
      ${controlsHtml()}
      ${previewAreaHtml()}
    `;
  }

  // ------------------------------------------------------------------ ACTIONS

  async function generateReport() {
    if (!ui.reportType) {
      ui.generateError = 'Please select a report type.';
      rerenderPageContent(view);
      return;
    }
    if (ui.reportType === 'attendance' || ui.reportType === 'leaves') {
      if (!ui.startDate || !ui.endDate) {
        ui.generateError = 'Please provide both start and end dates.';
        rerenderPageContent(view);
        return;
      }
      if (ui.startDate > ui.endDate) {
        ui.generateError = 'Start date must be before or equal to the end date.';
        rerenderPageContent(view);
        return;
      }
    }

    ui.generating = true;
    ui.generateError = '';
    ui.result = null;
    rerenderPageContent(view);

    try {
      const filters = buildFilters();
      let data;
      switch (ui.reportType) {
        case 'attendance':
          data = await adminStore.getReport('attendance', filters);
          break;
        case 'leaves':
          data = await adminStore.getReport('leaves', filters);
          break;
        case 'payroll':
          data = await adminStore.getReport('payroll', adminStore.reportFilters({
            month: ui.month,
            department: ui.department,
            employeeId: ui.employeeId,
          }));
          break;
        case 'employees':
          data = await adminStore.getReport('employees', adminStore.reportFilters({
            department: ui.department,
            search: ui.search,
          }));
          break;
        default:
          throw new Error('Unknown report type');
      }
      ui.result = { type: ui.reportType, data };
      showToast(`${REPORT_TYPES.find(t => t.value === ui.reportType)?.label || 'Report'} generated.`, 'success');
    } catch (err) {
      ui.generateError = err.message || 'Report generation failed.';
    }
    ui.generating = false;
    rerenderPageContent(view);
  }

  async function exportCsv() {
    if (!ui.result) return;
    try {
      await adminStore.downloadReportCsv(ui.result.type, buildFilters());
      showToast('CSV downloaded.', 'success');
    } catch (err) {
      showToast(err.message || 'Export failed.', 'danger');
    }
  }

  async function loadInitial() {
    try {
      const empPage = await adminStore.queryEmployees({ page: 1, limit: 300 });
      ui.employees = empPage.employees || [];
      ui.employeesLoaded = true;
    } catch (err) {
      ui.error = err.message || 'Failed to load employees.';
    }
    rerenderPageContent(view);
  }

  // -------------------------------------------------------------------- VIEW

  const view = {
    render() {
      if (!ui.employeesLoaded && !ui.error) return renderAdminLayout('/admin/reports', 'Reports', skeletonHtml());
      if (ui.error) return renderAdminLayout('/admin/reports', 'Reports', errorHtml());
      return renderAdminLayout('/admin/reports', 'Reports', contentHtml());
    },

    afterRender() {
      initAdminLayoutEvents();
      document.getElementById('rep-retry')?.addEventListener('click', () => { rerenderPageContent(view); loadInitial(); });
      if (!ui.employeesLoaded && !ui.error) {
        loadInitial();
        return;
      }
      view.bindEvents();
    },

    bindEvents() {
      document.getElementById('rep-type')?.addEventListener('change', e => {
        ui.reportType = e.target.value;
        ui.status = '';
        ui.leaveType = '';
        ui.result = null;
        ui.generateError = '';
        rerenderPageContent(view);
      });
      document.getElementById('rep-employee')?.addEventListener('change', e => { ui.employeeId = e.target.value; });
      document.getElementById('rep-dept')?.addEventListener('change', e => { ui.department = e.target.value; });
      document.getElementById('rep-status')?.addEventListener('change', e => { ui.status = e.target.value; });
      document.getElementById('rep-leave-type')?.addEventListener('change', e => { ui.leaveType = e.target.value; });
      document.getElementById('rep-month')?.addEventListener('change', e => { if (e.target.value) ui.month = e.target.value; });
      document.getElementById('rep-start')?.addEventListener('change', e => { ui.startDate = e.target.value; });
      document.getElementById('rep-end')?.addEventListener('change', e => { ui.endDate = e.target.value; });

      document.getElementById('rep-generate-btn')?.addEventListener('click', generateReport);
      document.getElementById('rep-export-csv-btn')?.addEventListener('click', exportCsv);

      // Search triggers on Enter (server-side contains search)
      document.getElementById('rep-search')?.addEventListener('keydown', e => {
        if (e.key === 'Enter') {
          ui.search = e.target.value.trim();
          generateReport();
        }
      });
    },

    unmount() { /* no subscriptions */ }
  };

  return view;
}
